"use client";

import WifiIcon from '@mui/icons-material/Wifi';
import { AppBar, Container, Toolbar, Typography } from '@mui/material';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import { useSelectedLayoutSegment } from 'next/navigation';
import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  const segment = useSelectedLayoutSegment()

  const pages = [
    'about',
    'tendencies',
    'technologies',
    'development'
  ];

  return (
    <html lang="en">
      <body className='h-screen w-screen'>
        <AppBar className='bg-black sticky t-0 h-1/10 justify-center'>
          <Toolbar disableGutters>
            <Typography
              variant="h6"
              noWrap
              sx={{
                mr: 2,
                display: { md: 'flex' },
                fontFamily: 'monospace',
                fontWeight: 700,
                letterSpacing: '.3rem',
                textDecoration: 'none',
              }}
            >
              <Link shallow href="/">
                <span>I</span>
                <WifiIcon />
                <span className='ml-1'>T</span>
              </Link>
            </Typography>
            <Box className='flex'>
              {pages.map((page) => (
                <Link shallow href={`/${page}`}>
                  <Button
                    disableRipple
                    key={page}
                    className={
                      page === segment!
                        ? "text-amber-400"
                        : "text-white"
                        +
                        " hover:text-amber-200"
                    }
                    sx={{ my: 2, color: 'white', display: 'block' }}
                  >
                    {page}
                  </Button>
                </Link>
              ))}
            </Box>
          </Toolbar>
        </AppBar>
        <main className='h-9/10'>
          {children}
        </main>
      </body>
    </html >
  )
}
