"use client";

import WifiIcon from '@mui/icons-material/Wifi';
import { AppBar, ThemeProvider, Toolbar, Typography, createTheme } from '@mui/material';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Link from 'next/link';
import { useSelectedLayoutSegment } from 'next/navigation';
import './globals.css';
import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface IChildren {
  children: React.ReactNode
}

export default function RootLayout({ children }: IChildren) {

  const segment = useSelectedLayoutSegment()

  const pages = [
    'about',
    'tendencies',
    'development'
  ];

  const theme = createTheme({
    palette: {
      mode: "dark",
      primary: {
        main: "#00000"
      },
      secondary: {
        main: "#fffff"
      }
    }
  })

  return (
    <html lang="en">
      <body className='h-screen w-screen'>
        <ThemeProvider theme={theme}>
          <AppBar
            sx={{ backgroundColor: "primary.dark" }}
            className='bg-black t-0 h-1/10 justify-center relative'
          >
            <Toolbar disableGutters>
              <Typography
                variant="h6"
                noWrap
                sx={{
                  mr: 2,
                  display: { md: 'flex' },
                  fontFamily: 'monospace',
                  fontWeight: 700,
                  letterSpacing: '.3rem',
                  textDecoration: 'none',
                }}
              >
                <Link style={{ marginLeft: 25 }} shallow href="/">
                  <span>I</span>
                  <WifiIcon sx={{ marginBottom: .5 }} />
                  <span className='ml-1'>T</span>
                </Link>
              </Typography>
              <Box className='flex'>
                {pages.map((page) => (
                  <Link shallow href={`/${page}`}>
                    <Button
                      disableRipple
                      key={page}
                      className={
                        page === segment!
                          ? "text-amber-400"
                          : "text-white"
                          + " hover:text-amber-200"
                      }
                      sx={{ my: 2, color: 'white', display: 'block' }}
                    >
                      {page}
                    </Button>
                  </Link>
                ))}
              </Box>
            </Toolbar>
          </AppBar>
          <main className='h-9/10 flex'>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html >
  )
}
